add_newline = false

[character] # The name of the module we are configuring is 'character'
success_symbol = '[λ](bold green)'

[git_branch]
symbol = " "

[git_status]
ahead = ""
behind = ""
conflicted = ""
renamed = ""
deleted = ""
