start-at-login = true 

after-login-command = [
	"exec-and-forget sketchybar",
  'exec-and-forget sh ~/.config/sketchybar/scripts/media-stream.sh'
]

on-focus-changed = [
  	'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  	'exec-and-forget sketchybar --trigger update_windows'
]

exec-on-workspace-change = [
  '/bin/zsh',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        [{ monitor."Built-in Retina Display" = 10}, 40] # for notch
outer.right =      10

[mode.main.binding]

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'

alt-n = 'workspace next'
alt-p = 'workspace prev'

alt-tab = 'workspace-back-and-forth'

alt-semicolon = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=service'] # command to notify sketchybar of mode change

# these open the apps if they are not already open
alt-t = '''exec-and-forget sh -c "open -a 'Ghostty'"'''
alt-c = '''exec-and-forget sh -c "open -a 'Cursor'"'''
alt-z = '''exec-and-forget sh -c "open -a 'Zen'"'''
alt-f = '''exec-and-forget sh -c "open -a 'Finder'"'''
alt-o = '''exec-and-forget sh -c "open -a 'Obsidian'"'''
alt-s = '''exec-and-forget sh -c "open -a 'Simulator'"'''
alt-m = '''exec-and-forget sh -c "open -a 'Spotify'"'''


[mode.service.binding]

esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
r = ['reload-config', 'flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main'] 
f = ['layout floating tiling', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main'] 
backspace = ['close-all-windows-but-current', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']

1 = ['move-node-to-workspace 1', 'workspace 1', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
2 = ['move-node-to-workspace 2', 'workspace 2', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
3 = ['move-node-to-workspace 3', 'workspace 3', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
4 = ['move-node-to-workspace 4', 'workspace 4', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
5 = ['move-node-to-workspace 5', 'workspace 5', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']

alt-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
alt-j = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
alt-k = ['join-with up', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']
alt-l = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_changed CURRENT_MODE=main']


# Space 1: Code

[[on-window-detected]] 
if.app-id = 'com.mitchellh.ghostty'
run = 'move-node-to-workspace 1'
[[on-window-detected]] 
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace 1'

# Space 2: Browser

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 2'

# Space 3: Organization

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.apple.reminders'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'md.obisidian'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.linear'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'come.linear'
run = 'move-node-to-workspace 3'

# Space 4: Communication

[[on-window-detected]]
if.app-id = 'net.whatsapp.WhatsApp'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = 'move-node-to-workspace 4'


# Space 5: Miscellaneous

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'move-node-to-workspace 5'

# Floating Windows

[[on-window-detected]]
if.app-id = 'com.chabomakers.Antinote'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iphonesimulator'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = 'layout floating'

[workspace-to-monitor-force-assignment]
1 = 'main' 
2 = 'main'   
3 = 'main'
4 = 'secondary'
5 = 'secondary'
